openapi: 3.0.2

info:
  version: 1.0.0
  title: Synergy!データベースAPI
  description: |
    # はじめに
    Synergy!データベースAPI は外部のシステムから、Synergy! のデータベース（マスター・履歴）の読み出し、登録・更新・削除などを簡単に行うことができる API です。  
    Synergy! の豊富な機能を生かしたシステム開発を簡易・短期間に行うことが可能です。

    ## API の利用にあたって
    API をご利用いただく場合、事前に Synergy! の利用登録が必要になります。  
    利用登録がまだお済みでない方は [Synergy! 公式ページ](https://www.synergy-marketing.co.jp/cloud/synergy/)よりお問い合わせください。

    また、API の利用には [Synergy! データベース API 契約規定](https://docs.synergy-marketing.co.jp/dbapi-reference/contract-provisions.html) が適用され、API を利用すると契約規定に同意したものとみなされます。

    ## 認証
    管理画面上の API 管理からクライアント認証キー、クライアントシークレットの発行を行なってください。
    発行時アクセス可能な IP アドレスを設定することで、指定した IP アドレス以外からのリクエストを制限することができます。

    Synergy!データベースAPI にアクセスするためには、リクエストヘッダーに発行したクライアント認証キー、クライアントシークレットを使用して取得したアクセストークンを付与する必要があります。  
    アクセストークンは事前に Synergy! 認可サーバ (https://auth.paas.crmstyle.com/oauth2/token) から OAuth 2.0 のクライアント・クレデンシャルズフローにより取得します。

    ### アクセストークン取得

    #### リクエストURL
    ```
    https://auth.paas.crmstyle.com/oauth2/token
    ```

    #### リクエストヘッダー
    | フィールド名    | 内容                               |
    |---------------|-----------------------------------|
    | Content-Type  | application/x-www-form-urlencoded |
    | Authorization | 管理画面上の API 管理からクライアント認証キー、クライアントシークレットの発行が可能となります。 <br> クライアント認証キー、クライアントシークレットを:（コロン）で繋いで、base64 でエンコードした文字列を指定します。 |

    #### リクエストパラメーター
    | プロパティ名 | 型     | 説明 |
    |------------|--------|------|
    | grant_type | String | OAuth 2.0 の処理フローを表します。 <br> "client_credentials" を指定してください。 |
    | audience   | String | アクセスするAPIのドメインを表します。 <br> "https://db.paas.crmstyle.com" を指定してください。 |
    | scope      | String | アクセスするAPIの種別を表します。 <br> 複数指定する場合は半角スペースを scope の間に含めて指定してください。 |

    #### scope一覧
    |         scope 名        | アクセス可能なAPI                                          |
    |-------------------------|---------------------------------------------------------|
    | db:apidefinition:design | ・ApiDefinition <br> ・OpenApi <br> ・DatabaseDefinition |
    | db:openapi:read         | ・OpenApi                                               |
    | db:record:execute       | ・Record                                                |

    #### リクエストサンプル
    ```
    AUTHHEADER=`echo -n ${CLIENT_ID}:${CLIENT_SECRET} | base64 -w0`  
    SCOPES="db:apidefinition:design db:openapi:read db:record:execute"
    curl -i -X POST \
      -H "Authorization: Basic ${AUTHHEADER}" \
      -H "Content-Type: application/x-www-form-urlencoded" \
      https://auth.paas.crmstyle.com/oauth2/token \
      -d "grant_type=client_credentials&scope=${SCOPES}&audience=https://db.paas.crmstyle.com"
    ```

    #### レスポンス
    レスポンスは JSON 形式で返却されます。

    ##### レスポンスサンプル
    ```
    {
      "access_token": "{Access Token}",
      "expires_in": 3599,
      "scope": "db:apidefinition:design db:openapi:read db:record:execute",
      "token_type": "bearer"
    }
    ```

    ##### レスポンス JSON プロパティ
    | プロパティ名   | 型      | 説明                                                                    |
    |--------------|---------|------------------------------------------------------------------------|
    | access_token | String  | Synergy!データベースAPI にアクセスするためのアクセストークンです。              |
    | expires_in   | Integer | アクセストークンの有効期限が切れるまでの秒数を表します。 <br> 有効期限は1時間です。 |
    | scope        | String  | アクセストークンに含まれる scope の一覧を表します。                           |
    | token_type   | String  | トークンの種別を表します。 <br> bearer 固定です。                            |

    ### Synergy!データベースAPI リクエスト
    リクエストの際、Authorization ヘッダーにアクセストークンをセットしてください。
    #### listApiDefinition リクエストサンプル
    ```
    curl -X GET \
      -H "accept: application/json" \
      -H "Authorization: Bearer ${ACCESS_TOKEN}" \
      https://db.paas.crmstyle.com/apis/apidefinition.database/v1/accounts/{accountCode}/apidefinitions
    ```

    <SecurityDefinitions />

    ## ご利用までの流れ

    ### 1. 認証情報取得
    [認証](#section/はじめに/認証)をご参照ください。

    ### 2. Record 定義登録
    データモデルを [OpenAPI V3 Schema](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) 形式で定義し [ApiDefinition.putApiDefinition](#operation/putApiDefinition) から定義を登録します。  
    定義を登録することで Synergy! データベースに項目が作成され API に紐付けされます。Synergy! データベースに作成されている既存項目を定義登録に使用したい場合、[既存項目を API に定義する](#section/API) を参照してください。

    ### 3. Record 利用
    2で登録された API を [Record](#tag/Record) より実行してください。

    #### APIクライアントについて
    作成された API は [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification) で定義されています。
    [OpenApi](#tag/OpenApi) より OpenAPI Document を取得することで、ご利用の開発言語に応じて API クライアントの自動生成が可能です。
    コード生成ツールは [OpenAPI.Tools](https://openapi.tools/) をご参照ください。

    ## リクエスト数制限
    同時リクエスト数の制限には、トークンバケットモデル（アカウントごとに、レート：10/sec、バースト：50）を採用しています。  
    ブロック発生時は、レスポンスコード：`429 Too Many Request` を返しますので、数分後に再度お試しください。

    ## 改訂履歴
    | 改訂日      | 更新内容 |
    |------------|---------|
    | 2020/05/19 | 初版作成 |
    
  termsOfService: https://docs.synergy-marketing.co.jp/dbapi-reference/contract-provisions.html
  contact:
    url: https://www.synergy-marketing.co.jp/cloud/synergy/
    email: api-support@i.msgs.jp
servers:
  - url: https://db.paas.crmstyle.com/
tags:
  - name: ApiDefinition
    description: |
      サーバ間連携用の独自の REST API を作成することができます。

  - name: OpenApi
    description: |
      ApiDefinition で作成した API 定義を OpenAPI Document 形式で参照することができます。

  - name: DatabaseDefinition
    description: |
      Synergy! 内に登録されているデータベース設定情報を参照することができます。

  - name: Record
    description: |
      ApiDefinition で作成した REST API を実行することができます。

  - name: Appendix
    description: |
      ## Synergy! 項目型一覧
      | Synergy! 項目型         | x-synergy-type              | 型      | 項目新規作成 | 備考 |
      |------------------------|-----------------------------|---------|:---------:|------|
      | Synergy!ID             | synergyId                   | integer | ×         | マスターデータベースを対象に API 定義する場合、プロパティ名を `id` にして定義してください |
      | HistoryID              | historyId                   | integer | ×         | 顧客データベースを対象に API 定義する場合、プロパティ名を `id` にして定義してください |
      | ＰＣメールアドレス型      | mailAddress                 | string  | ×          | email 形式<br>（e.g. synergy@example.com）|
      | 携帯メールアドレス型      | mobileMailAddress           | string  | ×          | email 形式<br>（e.g. synergy@example.com）|
      | 更新日時                | updatedDate                 | string  | ×          | ISO 8601 形式<br>（e.g. 2020-05-01T00:00:00+09:00）|
      | システム登録日時         | registeredDate              | string  | ×          | ISO 8601 形式<br>（e.g. 2020-05-01T00:00:00+09:00）|
      | メール受信拒否フラグ型    | mailRefusalFlag             | boolean | ×          | ご利用には Synergy! メール配信機能の契約が必要です |
      | ＰＣメールエラーカウント型 | mailAddressErrorCount       | integer | ×          | ご利用には Synergy! メール配信機能の契約が必要です |
      | 携帯メールエラーカウント型 | mobileMailAddressErrorCount | integer | ×          | ご利用には Synergy! メール配信機能の契約が必要です |
      | メルマガ解除フラグリスト型 | mlRefusalFlags              | array   | ×          | ご利用には Synergy! メール配信機能の契約が必要です |
      | 文字型                  | text                        | string  | ◯         |      |
      | 数値型                  | number                      | number  | ◯         |      |
      | 年月日型                | date                        | string  | ◯          | yyyy-MM-dd 形式（e.g. 2020-05-01）|
      | 月日型                  | monthDay                    | string  | ◯         | --MM-dd 形式（e.g. --05-01）|
      | タイムスタンプ型          | dateTime                    | string  | ◯         | ISO 8601 形式<br>（e.g. 2020-05-01T00:00:00+09:00）|
      | 単一選択型               | singleSelect                | array  | ◯          |      |
      | 複数選択型               | multipleSelect              | array   | ◯         |      |
      | パスワード型             | password                    | string  |  ◯         |      |
      | パスワードハッシュ型      | passwordHash                | string  | △          | ご利用には Synergy! のオプション契約が必要です |

      ## 既存項目を API に定義する
      Synergy!データベースAPI では、既に管理画面などからデータベースに設定されている項目を API に定義することができます。
      対象の項目名を [DatabaseDefinition](#tag/DatabaseDefinition) から取得し、`x-synergy-mapping` にセットしてください。

      ##### 既存項目マッピングサンプル
      ```
      "spec": {
        ...
        "schema": {
          "properties": {
            "existingTxtColumn": {
              "x-synergy-mapping": "_col1",
              "type": "string"
            },
            "existingDateColumn": {
              "x-synergy-mapping": "_col2",
              "type": "string",
              "format": "date"
            },
            "existingPasswordColumn": {
              "x-synergy-mapping": "_col3",
              "x-synergy-type": "password"
            }
            "existingSingleSelectColumn": {
              "x-synergy-mapping": "_col4",
              "x-synergy-type": "singleSelect"
            }
          }
        }
      }
      ```

      ## オペレータ一覧
      | オペレータ      | 説明                       |
      | ------------- | -------------------------- |
      | eq            | 等しい                     |
      | notEq         | 等しくない                 |
      | isNull        | 対象が Null である         |
      | lt            | より小さい                 |
      | lte           | 以下                       |
      | gt            | より大きい                 |
      | gte           | 以上                       |
      | in            | いずれかと等しい <br> ※ 右辺に複数の値を設定可能 |
      | notIn         | いずれとも等しくない <br> ※ 右辺に複数の値を設定可能 |
      | contains      | 含んでいる                |
      | notContains   | 含んでいない             |
      | startsWith    | 対象の文字列で始まる       |
      | notStartsWith | 対象の文字列で始まらない   |
      | endsWith      | 対象の文字列で終わる       |
      | notEndsWith   | 対象の文字列で終わらない   |
      | containsEvery | 対象をすべて含んでいる <br> ※ 右辺に複数の値を設定可能 |
      | containsSome  | 対象のいずれかを含んでいる <br> ※ 右辺に複数の値を設定可能 |

      ## 型ごとの使用可能オペレータ
      | 型                    | eq, <br> notEq | isNull | lt, lte, <br> gt, gte | in, <br> notIn | contains, <br> notContains | startsWith, <br> notStartsWith, <br> endsWith, <br> notEndsWith | containsEvery, <br> containsSome |
      |-----------------------|----------------|--------|-----------------------|----------------|---------------------------|------------------------------------------------------------------|----------------------------------|
      | Synergy!ID            | ○              | ×      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | HistoryID             | ○              | ×      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | ＰＣメールアドレス型      | ○             | ○      | ○                     | ○              | ○                         | ○                                                                | ×                                |
      | 携帯メールアドレス型      | ○             | ○      | ○                     | ○              | ○                         | ○                                                                | ×                                |
      | 更新日時                | ○             | ×      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | システム登録日時         | ○             | ×      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | メール受信拒否フラグ型    | ○             | ×      | ×                     | ×              | ×                         | ×                                                                | ×                                |
      | ＰＣメールエラーカウント型 | ○             | ×      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | 携帯メールエラーカウント型 | ○             | ×      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | メルマガ解除フラグリスト型 | ×             | ×      | ×                     | ×              | ○                         | ×                                                                | ○                                |
      | 文字型                  | ○             | ○      | ○                     | ○              | ○                         | ○                                                                | ×                                |
      | 数値型                  | ○             | ○      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | 年月日型                | ○             | ○      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | 月日型                  | ○             | ○      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | タイムスタンプ型         | ○             | ○      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | 単一選択型              | ○             | ○      | ○                     | ○              | ×                         | ×                                                                | ×                                |
      | 複数選択型              | ×             | ×      | ×                     | ×              | ○                         | ×                                                                | ○                                |

components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://auth.paas.crmstyle.com/oauth2/token"
          refreshUrl: "https://auth.paas.crmstyle.com/oauth2/token"
          scopes:
            db:apidefinition:design: ApiDefinition 全般実行、OpenApi 定義参照、データベース設定情報参照
            db:openapi:read: OpenApi 定義参照のみ可能
            db:record:execute: Record 全般実行
    bearer:
      type: http
      scheme: bearer

paths:
  /apis/apidefinition.database/v1/accounts/{accountCode}/apidefinitions:
    get:
      tags:
        - ApiDefinition
      description: 登録されている API 定義の一覧を取得します。
      operationId: listApiDefinition
      security:
        - oauth:
            - db:apidefinition:design
        - bearer: []
  /apis/apidefinition.database/v1/accounts/{accountCode}/apidefinitions/{name}:
    put:
      tags:
        - ApiDefinition
      description: |
        API 定義を登録・更新します。

        登録済みの API 定義にプロパティを追加・削除することで API 定義を更新することができます。  
        なお、プロパティを削除しても定義していたデータベース項目は削除されません。

        ## API 定義について
        Request samples を参考に API 定義を JSON 文字列で構築してリクエストボディに指定し、  
        リクエストヘッダーの `Content-Type` に `application/json` を指定してリクエストしてください。

        ### データベースの設定
        `spec.resources.main` にデータベースの名称および種別をセットします。

        #### データベース名（mapping）について
        * 既存の Synergy! 上のデータベースが対象の場合  
           [DatabaseDefinition](#tag/DatabaseDefinition) より定義したいデータベースの名称を取得して `mapping` にセットしてください。

        * 新しくデータベースを作成して定義を行う場合  
           存在しないデータベース名を `mapping` にセットすることで、データベースを新規作成して API に定義することができます。  
           新規作成できるのは type が historyDb の履歴型データベースのみです。  
           アンダースコアから始まるデータベース名は予約されており、データベース新規作成時に指定することはできません。

        #### データベース種別（type）について
        定義したいデータベースのデータベース種別を `type` にセットしてください。  
        参照型データベースは使用できません。

        | 定義名      | 説明              |
        |------------|------------------|
        | customerDb | マスターデータベース |
        | historyDb  | 履歴型データベース  |

        ### プロパティの定義
        `spec.schema.properties` にプロパティ名および型をセットします。

        #### プロパティ名について
        定義対象のプロパティ名（key）にセットしてください。  
        プロパティ名は英小文字で始まり英数字またはアンダースコアで構成される必要があります。`pattern: [a-z][a-zA-Z0-9_]*`  
        新規作成可能な型かつ {API 定義名}_{プロパティ名} と同一の項目名がデータベースに存在しない場合、項目を新規作成して定義されます。

        例）API 定義名が `api1` プロパティ名が `age` の場合、データベース上の項目名は `api1_age` となります。
        ```
        "metadata": {
          ...
          "name": "api1"
        },
        "spec": {
          ...
          "resources": {
            "properties": {
              "age": {
                "type": "number"
              },
              ...
            }
          }
        }
        ```

        #### 型について
        定義対象項目の項目型を [Synergy! 項目型一覧](#section/Synergy!) を参考に `x-synergy-type` にセットしてください。
        * `文字型`、`数値型`、`年月日型`、`タイムスタンプ型`は `type` および `format` を指定することで、x-synergy-type を省略することができます。
        | Synergy! 項目型 | type   | format   |
        |----------------|--------|----------|
        | 文字型          | string | -        |
        | 数値型          | number | -        |
        | 年月日型        | string | date      |
        | 月日型          | string | month-day |
        | タイムスタンプ型 | string | date-time |

        #### 既存項目を定義する場合
        [既存項目を API に定義する](#section/API)

        ## 登録数上限
        | 項目   | 上限数 |
        | ---- | ---- |
        | 登録可能な最大 API 定義数  |  10  |
        | 1API のプロパティ（ApiDefinition.spec.schema.properties）数上限  |  100  |

      operationId: putApiDefinition
      security:
        - oauth:
            - db:apidefinition:design
        - bearer: []
    get:
      tags:
        - ApiDefinition
      description: 指定した定義名と一致する API 定義を取得します。
      operationId: getApiDefinition
      security:
        - oauth:
            - db:apidefinition:design
        - bearer: []
    delete:
      tags:
        - ApiDefinition
      description: |
        指定された定義名と一致する API 定義を削除します。  
        API 定義を削除しても定義されていたデータベース項目は削除されません。
      operationId: deleteApiDefinition
      security:
        - oauth:
            - db:apidefinition:design
        - bearer: []
  /apis/apidefinition.database/v1/accounts/{accountCode}/apidefinitions/{name}/openapiv3: 
    get:
      tags:
        - OpenApi
      description: 指定された API 定義の OpenAPI Document を取得します。
      operationId: getOpenApi
      security:
        - oauth:
            - db:apidefinition:design
        - oauth:
            - db:openapi:read
        - bearer: []
  /apis/apidefinition.database/v1/accounts/{accountCode}/openapiv3:
    get:
      tags:
        - OpenApi
      description: 登録されている全てのAPI定義が内包されたOpenAPI Documentを取得します。
      operationId: getAllOpenApi
      security:
        - oauth:
            - db:apidefinition:design
        - oauth:
            - db:openapi:read
        - bearer: []
  /apis/apidefinition.database/v1/accounts/{accountCode}/databasedefinitions:
    get:
      tags:
        - DatabaseDefinition
      description: Synergy! 内に登録されているデータベース設定情報の一覧を取得します。
      operationId: listDatabaseDefinition
      security:
        - oauth:
            - db:apidefinition:design
        - bearer: []
  /apis/apidefinition.database/v1/accounts/{accountCode}/databasedefinitions/{name}:
    get:
      tags:
        - DatabaseDefinition
      description: 指定されたデータベース設定情報を取得します。
      operationId: getDatabaseDefinition
      security:
        - oauth:
            - db:apidefinition:design
        - bearer: []
  /apis/record.database/v1/accounts/{accountCode}/{name}/records:
    post:
      tags:
        - Record
      description: レコードを新規登録します。
      operationId: createRecord
      security:
        - oauth:
            - db:record:execute
        - bearer: []

  /apis/record.database/v1/accounts/{accountCode}/{name}/query:
    post:
      tags:
        - Record
      description: |
        レコードを検索します。  
        filter オブジェクトを使用することで検索条件を設定できます。
      operationId: queryRecords
      security:
        - oauth:
            - db:record:execute
        - bearer: []

  /apis/record.database/v1/accounts/{accountCode}/{name}/count:
    post:
      tags:
        - Record
      description: |
        レコード件数を取得します。  
        filter オブジェクトを使用することで検索条件を設定できます。
      operationId: countRecords
      security:
        - oauth:
            - db:record:execute
        - bearer: []

  /apis/record.database/v1/accounts/{accountCode}/{name}/records/{id}:
    get:
      tags:
        - Record
      description: ID で指定されたレコードを取得します。
      operationId: findRecord
      security:
        - oauth:
            - db:record:execute
        - bearer: []

    patch:
      tags:
        - Record
      description: |
        ID で指定されたレコードを更新します。  
      operationId: patchRecord
      security:
        - oauth:
            - db:record:execute
        - bearer: []

    delete:
      tags:
        - Record
      description: ID で指定されたレコードを削除します。
      operationId: deleteRecord
      security:
        - oauth:
            - db:record:execute
        - bearer: []
